version: '3.8'

services:
  app:
    image: webdevops/php-nginx-dev:8.4
    container_name: app
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/web
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "80:80"
    working_dir: /var/www/html/
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge